version: 1
update_configs:
  - package_manager: "javascript"
    directory: "/library"
    update_schedule: "live"
  - package_manager: "javascript"
    directory: "/frontend"
    update_schedule: "live"
  - package_manager: "java:maven"
    directory: "/api"
    update_schedule: "daily"